name: Build
on: [push]
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: secondlife/action-autobuild@which-branch
        with:
          platform: common
          token: ${{ github.token }}
  release:
    needs: build
    runs-on: [ubuntu-latest]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: secondlife/action-autobuild-release@v1
        with:
          public: true
